# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  test_sites:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  test_site_workflow:
    triggers:
      - schedule:
          cron: "25 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_sites
